blank_issues_enabled: true
contact_links:
  - name: Documentation 
    url: https://iroiro.dev/SwiftWindowLauncher/documentation/
    about: More information on using SwiftWindowLauncher can be found here.